#!/bin/bash
# BotScalp AWS GPU - Quick Reference Commands

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   BotScalp AWS GPU - Quick Reference                      ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 SETUP (Execute uma única vez)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cd /opt/botscalpv3 && bash setup_aws_gpu.sh"
echo ""

echo "🚀 LANÇAR INSTÂNCIA GPU"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "source .venv/bin/activate"
echo "python aws_gpu_launcher.py \\"
echo "  --region us-east-1 \\"
echo "  --instance-type g4dn.xlarge \\"
echo "  --key-name falcom \\"
echo "  --name v3 \\"
echo "  --spot \\"
echo "  --max-price 1.50 \\"
echo "  --volume-size 50 \\"
echo "  --ssh-cidr 0.0.0.0/0"
echo ""

echo "🔄 REUTILIZAR INSTÂNCIA EXISTENTE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "source .venv/bin/activate"
echo "python aws_gpu_launcher.py --region us-east-1 --key-name falcom --name v3 --reuse"
echo ""

echo "🔐 CONECTAR VIA SSH"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Ler IP da última instância"
echo "IP=\$(cat tools/last_gpu.json | grep public_ip | cut -d'\"' -f4)"
echo "ssh -i ~/.ssh/falcom.pem ubuntu@\$IP"
echo ""
echo "# Ou usar diretamente:"
echo "ssh -i ~/.ssh/falcom.pem ubuntu@13.218.186.75"
echo ""

echo "✅ VALIDAÇÕES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Testar credenciais AWS"
echo "aws sts get-caller-identity"
echo ""
echo "# Verificar instâncias ativas"
echo "aws ec2 describe-instances --region us-east-1 --query 'Reservations[*].Instances[*].[InstanceId,State.Name,PublicIpAddress]' --output table"
echo ""
echo "# Ver GPU na instância"
echo "ssh -i ~/.ssh/falcom.pem ubuntu@13.218.186.75 nvidia-smi"
echo ""

echo "🗑️  LIMPEZA"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "# Terminar instância (para de cobrar!)"
echo "aws ec2 terminate-instances --instance-ids i-01e32eea0712f1fb5 --region us-east-1"
echo ""

echo "📚 DOCUMENTAÇÃO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "cat SETUP_AWS_GPU.md         # Guia completo"
echo "cat STATUS_FINAL.md          # Status final do projeto"
echo "cat tools/last_gpu.json      # Metadata da última instância"
echo ""

echo "💰 PREÇOS APROXIMADOS (us-east-1, spot)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "g4dn.xlarge (1x T4):  ~\$0.40-0.60/hr"
echo "g4dn.2xlarge (1x T4): ~\$0.70-1.00/hr"
echo "g5.xlarge (1x L40):   ~\$1.00-1.50/hr"
echo "g5.2xlarge (1x L40):  ~\$1.50-2.00/hr"
echo ""

echo "╔════════════════════════════════════════════════════════════╗"
echo "║ Tudo pronto! Execute: bash setup_aws_gpu.sh               ║"
echo "╚════════════════════════════════════════════════════════════╝"
