#cloud-config
package_update: true
package_upgrade: true
packages:
- build-essential
- git
- python3
- python3-venv
- python3-pip
- docker.io
- unzip
- curl
- awscli
runcmd:
- [ bash, -lc, 'set -euxo pipefail' ]
- [ bash, -lc, 'systemctl enable docker && systemctl start docker' ]
- [ bash, -lc, 'usermod -aG docker ubuntu || true' ]
- [ bash, -lc, 'apt-get install -y linux-headers-$(uname -r)' ]
- [ bash, -lc, 'curl -fsSL https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb -o /tmp/cuda-keyring.deb' ]
- [ bash, -lc, 'dpkg -i /tmp/cuda-keyring.deb' ]
- [ bash, -lc, 'apt-get update' ]
- [ bash, -lc, 'DEBIAN_FRONTEND=noninteractive apt-get install -y cuda-toolkit-12-3 nvidia-driver-535-server nvidia-dkms-535-server' ]
- [ bash, -lc, 'curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey | gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit.gpg' ]
- [ bash, -lc, 'curl -fsSL https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list -o /etc/apt/sources.list.d/nvidia-container-toolkit.list' ]
- [ bash, -lc, 'apt-get update' ]
- [ bash, -lc, 'DEBIAN_FRONTEND=noninteractive apt-get install -y nvidia-container-toolkit' ]
- [ bash, -lc, 'nvidia-ctk runtime configure --runtime=docker' ]
- [ bash, -lc, 'systemctl restart docker' ]
- [ bash, -lc, 'echo "BotScalp GPU bootstrap concluído"' ]
